export const GET_CURRENT_USER_ACTION = "GET_CURRENT_USER_ACTION";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const GET_USER_ACTION = "GET_USER_ACTION";
export const GET_USERS_LIST_ACTION = "GET_USERS_LIST_ACTION";
export const CREATE_USER_ACTION = "CREATE_USER_ACTION";


export const ADD_HERO_ACTION = "ADD_HERO_ACTION";
